[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["zenplate", "zenplate.plugins", "zenplate.plugins.default_plugins", "zenplate.scripts"]
package-dir = {"zenplate" = "zenplate", "zenplate.plugins" = "zenplate/plugins", "zenplate.plugins.default_plugins" = "zenplate/plugins/default_plugins", "zenplate.scripts" = "extras/scripts"}

[project]
name = 'zenplate'
description = 'A pluggable CLI templating tool leveraging the powers of Jinja2 and YAML'
authors = [
    {name = 'Cam Ratchford', email = 'camratchford@gmail.com'},
]

classifiers = [
    'Development Status :: 3 - Alpha',
    'Programming Language :: Python',
    'Programming Language :: Python :: 3 :: Only',
    'Intended Audience :: Developers',
    'Intended Audience :: Information Technology',
    'Intended Audience :: System Administrators',
    'Operating System :: POSIX :: Linux',
    'Environment :: Console',
    'Topic :: Software Development :: Build Tools',
    'Topic :: Utilities',
]
version = "0.3.0"
requires-python = '>=3.10'
dependencies = [
    "byoconfig==1.2.3",
    "Jinja2==3.1.2",
    "PyYAML==6.0.1",
    "typer==0.15.1",
]

[project.optional-dependencies]
development = [
    "mkdocs",
    "mkdocs-material",
    "ruff",
    "isort",
    "pytest",
    "build",
    "twine"
]

[project.urls]
Homepage = 'https://github.com/camratchford/zenplate'
Source = 'https://github.com/camratchford/zenplate'

[project.scripts]
zenplate = "zenplate.cli:cli"
zenplate-version-bump = "zenplate.scripts.bump_version:cli"
zenplate-build = "zenplate.scripts.build:cli"
zenplate-format-and-lint = "zenplate.scripts.format_and_lint:cli"
zenplate-test = "zenplate.scripts.test:cli"

[tool.ruff]
line-length = 119
exclude = [
    "tests/fixtures/**/*"
]

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F"]
ignore = []
fixable = ["ALL"]
unfixable = []
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = false
docstring-code-line-length = "dynamic"

[tool.isort]
profile = "black"
line_length = 119

[tool.pytest.ini_options]
addopts = "-ra -q"
testpaths = [
    "tests",
]
