name: Build and Publish
on:
  pull_request:
    branches: [ "main" ]
permissions:
  contents: read
jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[development]
    - name: Build docs
      run: |
        extras/scripts/mkdocs.sh
    - name: Build pyinstaller
      run: |
        powershell extras/scripts/pyinstaller.sh
    - name: Build pypi
      run: |
        powershell extras/scripts/pypi.sh
  build_windows:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[development]
    - name: Build docs
      run: |
        powershell extras/scripts/mkdocs.ps1
    - name: Build pyinstaller
      run: |
        powershell extras/scripts/pyinstaller.ps1
    - name: Build pypi
      run: |
        powershell extras/scripts/pypi.ps1