name: Build and Publish
on:
  pull_request:
    branches: [ "main" ]
permissions:
  contents: read
  id-token: write  # Required for publishing to PyPI
jobs:
  build_linux:
    runs-on:
      - self-hosted
      - linux
      - x64
    defaults:
      run:
        shell: bash
    environment:
      name: default
      url: https://pypi.org/p/zenplate
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[development]
    - name: Build docs
      run: extras/scripts/mkdocs.sh
    - name: Build pyinstaller
      run: extras/scripts/pyinstaller.sh
    - name: Publish docs
      run: ${{ secrets.DEPLOY_CMD }}
    - name: pypi-publish
      uses: pypa/gh-action-pypi-publish@v1.12.3
  pyinstaller_windows:
    runs-on:
      - self-hosted
      - windows
      - x64
    defaults:
      run:
        shell: powershell
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[development]
    - name: Build pyinstaller
      run: extras/scripts/pyinstaller.ps1
