name: Lint and Test
on:
  push:
    branches:
      - '*.**.*'
permissions:
  contents: read
jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[development]
        pip install tests/fixtures/plugin_module_for_matched_import
    - name: Lint with ruff
      run: ruff check --fix
    - name: Format with ruff
      run: ruff format
    - name: Test with pytest
      run: pytest
  build_windows:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[development]
        pip install tests/fixtures/plugin_module_for_matched_import
    - name: Lint with ruff
      run: ruff check --fix
    - name: Format with ruff
      run: ruff format
    - name: Test with pytest
      run: pytest